movies_project/movies_app/urls.py
from django.urls import path
from . import views

app_name = 'movie'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.details, name='details'),
    path('add', views.add, name='add'),
    path('delete/<int:movie_id>/', views.delete, name='delete'),
    path('update/<int:movie_id>/', views.update, name='update'),

]

movies_project/movies_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from movies_project import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movies_app.urls")),

]
if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movies_project/movies_app/models.py
from django.db import models

# Create your models here.


class MovieModel(models.Model):
    name = models.CharField(max_length=250)
    year = models.IntegerField()
    desc = models.TextField()
    img = models.ImageField(upload_to="MovieImg")

    def __str__(self):
        return self.name

movies_project/movies_app/forms.py
from django import forms
from .models import MovieModel


class MovieForm(forms.ModelForm):
    class Meta:
        model = MovieModel
        fields = '__all__'

movies_project/movies_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import MovieModel
from .forms import MovieForm


# Create your views here.


def index(request):
    movie = MovieModel.objects.all()
    movie_details = {
        'movie': movie
    }
    return render(request, 'index.html', movie_details)


def details(request, movie_id):
    movie = MovieModel.objects.get(id=movie_id)
    return render(request, 'details.html', {"movie": movie})


def add(request):
    if request.method == 'POST':
        name = request.POST['name']
        year = request.POST['year']
        desc = request.POST['desc']
        image = request.FILES['image']

        movie = MovieModel(name=name, year=year, desc=desc, img=image)
        movie.save()

        return redirect('/')
    return render(request, 'add.html')


def delete(request, movie_id):
    if request.method == 'POST':
        bike = MovieModel.objects.get(id=movie_id)
        bike.delete()
        return redirect('/')

    return render(request, 'delete.html')


def update(request, movie_id):
    movie = MovieModel.objects.get(id=movie_id)
    forms = MovieForm(request.POST or None, request.FILES, instance=movie)

    if forms.is_valid():
        forms.save()

        return redirect('/')

    return render(request, 'update.html', {'movie': movie, 'forms': forms})

movies_project/templates/add.html
{% extends 'base.html' %}

<!--title-->
{% block title %}
    ADD
{% endblock %}

<!--body-->
{% block body %}
    <h1 class="head text-center">Add Data</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" name="name" class="form-control" placeholder="Enter the Name">
                    </div><br>
                    <div class="form-group">
                        <input type="text" name="year" class="form-control" placeholder="Enter the year">
                    </div><br>
                    <div class="form-group">
                        <input type="text" name="desc" class="form-control" placeholder="Enter the Description">
                    </div><br>
                    <div class="form-group">
                        <input type="file" name="image">
                    </div><br>
                    <div>
                        <input type="submit" class="btn btn-primary">
                    </div>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
{% endblock %}

movies_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
<nav class="navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'movie:index' %}">
      <b>MOVIES</b>
    </a>
  </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

movies_project/templates/delete.html
{% extends 'base.html' %}

<!--title-->
{% block title %}
    DELETE
{% endblock %}

<!--body-->
{% block body %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure do you want to delete ?</p>
        <input type="submit" class="btn btn-danger">
    </form>
{% endblock %}

movies_project/templates/details.html
{% extends 'base.html' %}

<!--title-->
{% block title %}
    DETAILS
{% endblock %}

<!--body-->
{% block body %}
<div class="container" style="padding-top: 20px;" xmlns="http://www.w3.org/1999/html">
    <div class="row">
        <div class="col-md-6" style="padding: 10px;">
            <img src="{{movie.img.url}}" alt="BikeImg" height="500px" width="430px" >
        </div>
        <div class="col-md-6">
            <h1><b>{{movie.name}}</b></h1>
            <h3>{{movie.year}}</h3>
            <p style="font-size:130%">{{movie.desc}}The class global attribute  is a space-separated list of the case-sensitive classes of the element. Classes allow CSS and JavaScript to select and access specific elements via the class selectors  or functions like the DOM method document.getElementsByClassName.</p>
            <br>
            <a href="{% url 'movie:update' movie.id %}" class="btn btn-warning">UPDATE</a>
            <a href="{% url 'movie:delete' movie.id %}" class="btn btn-danger">DELETE</a>
        </div>
    </div><br>
</div>
{% endblock %}

movies_project/templates/index.html
{% extends 'base.html' %}

<!--title-->
{% block title %}
INDEX
{% endblock %}

<!--body-->
{% block body %}
<h1 class="head text-center">WELCOME</h1><br>
<div class="container">
    <div class="row">
        {% for i in movie %}
        <div class="col-md-4">
            <div class="card shadow" style="width: 20rem;">
                <a href="{% url 'movie:details' i.id %}"><img src="{{i.img.url}}" class="card-img-top" alt="cardImg" height="300px" width="100%"></a>
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.year}}</p>
                    <a href="{% url 'movie:details' i.id %}" class="btn btn-primary">check it</a>
                </div>
            </div><br>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

movies_project/templates/update.html
{% extends 'base.html' %}

<!--title-->
{% block title %}
    ADD
{% endblock %}

<!--body-->
{% block body %}
    <h1 class="head text-center">Add Data</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {{forms.as_p}}
                    </div><br>
                    <div>
                        <input type="submit" class="btn btn-primary">
                    </div>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div><br>
{% endblock %}